# FWL partialling-out: the backbone of the DML PLR model.
#
# fwl_theta()    residual-on-residual estimate + sandwich variance for one
#                completed dataset (S continuous, possibly a surrogate draw).
# crossfit()     K-fold out-of-sample predictions for a nuisance function,
#                with a pluggable fitter: fit(X, y) -> function(Xnew) -> pred.
# plr_crossfit() full PLR estimator: cross-fit E[S|X] and E[D|X], then FWL.

fwl_theta <- function(S_res, D_res) {
  denom <- sum(D_res^2)
  theta <- sum(S_res * D_res) / denom
  resid <- S_res - theta * D_res
  var_theta <- sum((D_res * resid)^2) / denom^2
  list(theta = theta, var = var_theta, se = sqrt(var_theta))
}

make_folds <- function(n, k) {
  split(sample.int(n), rep_len(seq_len(k), n))
}

# fitter: function(X, y) returning a predict function(Xnew) -> numeric
crossfit <- function(X, y, fitter, folds) {
  pred <- numeric(length(y))
  for (test in folds) {
    fit <- fitter(X[-test, , drop = FALSE], y[-test])
    pred[test] <- fit(X[test, , drop = FALSE])
  }
  pred
}

# Nuisance fitters ------------------------------------------------------------

fit_lm <- function(X, y) {
  d <- data.frame(y = y, X)
  m <- lm(y ~ ., data = d)
  function(Xnew) predict(m, newdata = data.frame(Xnew))
}

# additive gam with a smooth per column
fit_gam <- function(X, y) {
  d <- data.frame(y = y, X)
  rhs <- paste(sprintf("s(%s)", names(d)[-1]), collapse = " + ")
  m <- mgcv::gam(as.formula(paste("y ~", rhs)), data = d)
  function(Xnew) as.numeric(predict(m, newdata = data.frame(Xnew)))
}

fit_gam_binomial <- function(X, y) {
  d <- data.frame(y = y, X)
  rhs <- paste(sprintf("s(%s)", names(d)[-1]), collapse = " + ")
  m <- mgcv::gam(as.formula(paste("y ~", rhs)), family = binomial, data = d)
  function(Xnew) as.numeric(predict(m, newdata = data.frame(Xnew),
                                    type = "response"))
}

fit_ranger <- function(X, y) {
  d <- data.frame(y = y, X)
  m <- ranger::ranger(y ~ ., data = d, num.trees = 200, min.node.size = 5)
  function(Xnew) predict(m, data = data.frame(Xnew))$predictions
}

# Full PLR: S = theta*D + l(X) + eta, D = m(X) + v ----------------------------

plr_crossfit <- function(S, D, X, fit_l = fit_gam, fit_m = fit_gam,
                         n_folds = 5, folds = NULL) {
  X <- as.data.frame(X)
  if (is.null(folds)) folds <- make_folds(nrow(X), n_folds)
  S_res <- S - crossfit(X, S, fit_l, folds)
  D_res <- D - crossfit(X, D, fit_m, folds)
  c(fwl_theta(S_res, D_res), list(S_res = S_res, D_res = D_res, folds = folds))
}

# ---- truncation pass-through (sudo.md section 6) -------------------------
#
# The surrogate is drawn at V_hat and truncated to the side Y selects.
# Because Y is generated by the TRUTH, it drags S back toward the correct
# interval, so full-model index error reaches theta damped by a factor
#   c(e) = 1 - dlogis(e) * (mu_+(e) - mu_-(e)),
# where mu_+(v) = E[eps | eps > -v], mu_-(v) = E[eps | eps <= -v].
# c rises from 0.307 at e=0 to ~1 for large |e|: once Y is nearly
# deterministic it adds no information beyond V_hat and the self-correction
# switches off. Verified against a numerical derivative of psi to 1e-11.
#
# Evaluated on a grid and interpolated -- calling integrate() pointwise
# over hundreds of thousands of rows is far too slow to be usable.

pass_mu_p <- function(v)
  integrate(function(x) x * dlogis(x), -v, Inf, rel.tol = 1e-10)$value / plogis(v)
pass_mu_m <- function(v)
  integrate(function(x) x * dlogis(x), -Inf, -v, rel.tol = 1e-10)$value / plogis(-v)

# E[S | D, X] as a function of the fitted index v and the true index e
pass_psi <- function(v, e)
  v + plogis(e) * pass_mu_p(v) + plogis(-e) * pass_mu_m(v)

.pass_grid <- local({
  g <- seq(0, 15, by = 0.05)
  list(e = g, c = vapply(g, function(e)
    1 - dlogis(e) * (pass_mu_p(e) - pass_mu_m(e)), numeric(1)))
})

# vectorised pass-through factor; symmetric in e, ->1 in the tails
pass_c <- function(e) {
  a <- abs(e)
  ifelse(a > 15, 1, approx(.pass_grid$e, .pass_grid$c, a, rule = 2)$y)
}

# cbar_1 = E[w * c(theta + g)] / E[w], w = m(1-m): the multiplier on the
# full model's D-coefficient error. Pass the treated-arm true index.
pass_cbar1 <- function(eta_treated, m) {
  w <- m * (1 - m)
  sum(w * pass_c(eta_treated)) / sum(w)
}
